import { describe, expect, it } from "vitest";
import { ADMIN_ROUTE_ROLES } from "../src/admin-panel.js";
import { ADMIN_ROLES } from "../src/admin-auth.js";

describe("admin panel route RBAC", () => {
  it("defines explicit minimum roles for every protected admin endpoint", () => {
    expect(ADMIN_ROUTE_ROLES).toEqual({
      "GET /auth/me": "VIEWER",
      "POST /auth/totp/setup": "VIEWER",
      "POST /auth/totp/confirm": "VIEWER",
      "POST /auth/totp/disable": "VIEWER",
      "GET /api/dashboard/summary": "VIEWER",
      "GET /api/guild": "VIEWER",
      "GET /api/control/overview": "VIEWER",
      "GET /api/control/members": "MODERATOR",
      "POST /api/control/members/:userId/moderation": "MODERATOR",
      "POST /api/control/members/:userId/roles": "ADMIN",
      "POST /api/control/members/:userId/roles/bulk": "ADMIN",
      "POST /api/control/channels/:channelId/purge": "MODERATOR",
      "POST /api/control/channels/:channelId/permissions": "ADMIN",
      "PATCH /api/control/channels/:channelId/position": "ADMIN",
      "POST /api/control/tickets/:ticketId/status": "MODERATOR",
      "POST /api/control/roles": "ADMIN",
      "PATCH /api/control/roles/:roleId": "ADMIN",
      "POST /api/control/roles/:roleId/delete": "ADMIN",
      "POST /api/control/channels": "ADMIN",
      "PATCH /api/control/channels/:channelId": "ADMIN",
      "POST /api/control/channels/:channelId/delete": "ADMIN",
      "PATCH /api/control/guild": "ADMIN",
      "POST /api/control/structure/plan": "ADMIN",
      "POST /api/control/messages/send": "MODERATOR",
      "GET /api/operations/overview": "MODERATOR",
      "POST /api/operations/console": "MODERATOR",
      "POST /api/operations/messages/preview": "MODERATOR",
      "POST /api/operations/messages/push": "ADMIN",
      "GET /api/operations/messages/pushes": "MODERATOR",
      "GET /api/operations/messages/approvals": "MODERATOR",
      "POST /api/operations/messages/approvals": "MODERATOR",
      "POST /api/operations/messages/approvals/:approvalId/review": "ADMIN",
      "GET /api/operations/templates": "MODERATOR",
      "POST /api/operations/templates": "MODERATOR",
      "POST /api/operations/templates/:templateId/delete": "ADMIN",
      "GET /api/custom/overview": "MODERATOR",
      "GET /api/custom/commands": "MODERATOR",
      "POST /api/custom/commands": "ADMIN",
      "POST /api/custom/commands/:commandId/delete": "ADMIN",
      "GET /api/custom/interactions": "MODERATOR",
      "POST /api/custom/interactions": "ADMIN",
      "POST /api/custom/interactions/:interactionId/delete": "ADMIN",
      "GET /api/custom/events": "MODERATOR",
      "GET /api/modules/overview": "MODERATOR",
      "GET /api/modules/events": "MODERATOR",
      "GET /api/commands/overview": "MODERATOR",
      "POST /api/modules/:moduleId/state": "ADMIN",
      "POST /api/modules/export": "ADMIN",
      "POST /api/modules/import": "ADMIN",
      "GET /api/settings": "VIEWER",
      "GET /api/permissions": "VIEWER",
      "PATCH /api/settings": "ADMIN",
      "PATCH /api/permissions": "ADMIN",
      "PATCH /api/xp/settings": "ADMIN",
      "POST /api/automations/flows": "ADMIN",
      "POST /api/automations/flows/:flowId/delete": "ADMIN",
      "POST /api/automations/preview": "MODERATOR",
      "POST /api/automations/test": "ADMIN",
      "PATCH /api/economy/settings": "ADMIN",
      "PATCH /api/automod/settings": "ADMIN",
      "GET /api/moderation/cases": "MODERATOR",
      "GET /api/tickets": "MODERATOR",
      "GET /api/audit/events": "MODERATOR",
      "GET /api/automations/overview": "MODERATOR",
      "GET /api/automod/events": "MODERATOR",
      "GET /api/anti-spam/events": "MODERATOR",
      "GET /api/proposals": "VIEWER",
      "GET /api/announcements": "VIEWER",
      "GET /api/blockchain/status": "VIEWER",
      "GET /api/wallets": "VIEWER",
      "GET /api/push/public-key": "VIEWER",
      "POST /api/push/subscriptions": "VIEWER",
      "DELETE /api/push/subscriptions": "VIEWER",
      "POST /api/push/test": "ADMIN",
      "POST /api/embeds/send": "ADMIN"
    });;
  });

  it("uses only supported admin roles", () => {
    expect(Object.values(ADMIN_ROUTE_ROLES).every((role) => ADMIN_ROLES.includes(role))).toBe(true);
  });
});
